version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/authdb
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis

  books:
    build:
      context: .
      dockerfile: services/books/Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/booksdb
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - redis

  orders:
    build:
      context: .
      dockerfile: services/orders/Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/ordersdb
    ports:
      - "8003:8003"
    depends_on:
      - postgres
      - redis
      - books

  reviews:
    build:
      context: .
      dockerfile: services/reviews/Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/reviewsdb
    ports:
      - "8004:8004"
    depends_on:
      - postgres
      - redis

  gateway:
    build: services/gateway
    container_name: api_gateway
    environment:
      - AUTH_SERVICE_URL=http://localhost:8001
      - BOOKS_SERVICE_URL=http://localhost:8002
      - ORDERS_SERVICE_URL=http://localhost:8003
      - REVIEWS_SERVICE_URL=http://localhost:8004
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=supersecret
    ports:
      - "8000:8000"
    depends_on:
      - auth
      - books
      - orders
      - reviews
      - redis

volumes:
  pgdata:
